name: proyectos
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  camera: ^0.11.3
  geolocator: ^14.0.2
  sensors_plus: ^7.0.0
  vector_math: ^2.1.4
  flutter_map: ^6.1.0
  latlong2: 0.9.1
  sqflite: ^2.4.0+1
  path_provider: ^2.0.15
  path: ^1.8.4
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  flutter_compass: ^0.7.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

dependency_overrides:
  flutter_compass: ^0.8.1

# CONFIGURACIÓN DEL ICONO DE LA APP
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/compass.png
    - assets/constelaciones/
    - assets/logo/app_icon.png
